import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Harshit',
      email: 'harshit@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'User',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456789'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'EARPHONES',
      slug: 'BOAT-EARPHONES',
      category: 'tech',
      image:
        'https://n1.sdlcdn.com/imgs/j/b/5/RPM-Euro-Games-Gaming-Earphone-SDL207268455-1-d365a.jpeg',
      price: 699,
      countInStock: 10,
      brand: 'boat',
      rating: 3.5,
      numReviews: 17,
      description: 'Nice Earphone',
    },
    {
      // _id: '2',
      name: 'Nike Shirt',
      slug: 'Nike-Shirt',
      category: 'clothes',
      image:
        'https://static.nike.com/a/images/c_limit,w_400,f_auto/t_product_v1/5f90e618-0a56-4b09-a884-49acffc3eaba/image.jpg',
      price: 350,
      countInStock: 7,
      brand: 'nike',
      rating: 2.5,
      numReviews: 11,
      description: 'Nice shirt',
    },
    {
      // _id: '3',
      name: 'Black Jeans',
      slug: 'Black-Jeans',
      category: 'clothes',
      image:
        'https://5.imimg.com/data5/FY/IH/MY-26625163/rugged-denim-black-500x500.jpg',
      price: 1000,
      countInStock: 2,
      brand: 'nike',
      rating: 4,
      numReviews: 13,
      description: 'Nice jeans',
    },
    {
      // _id: '4',
      name: 'Logi-Tech Mouse',
      slug: 'Logi-Tech-Mouse',
      category: 'tech',
      image:
        'https://gamesncomps.com/wp-content/uploads/2022/08/2-2022-08-12T171115.697.jpg',
      price: 150,
      countInStock: 7,
      brand: 'Logi',
      rating: 2,
      numReviews: 11,
      description: 'Nice Mouse',
    },
    {
      // _id: '5',
      name: 'Eksa E900 Pro Headphone',
      slug: 'Eksa-E900-Pro-Headphone',
      category: 'tech',
      image:
        'https://rukminim1.flixcart.com/image/416/416/kvcpn680/headphone/7/4/b/e900-green-eksa-original-imag89r3rprqegtf.jpeg?q=70',
      price: 1500,
      countInStock: 7,
      brand: 'eska',
      rating: 5,
      numReviews: 11,
      description: 'Nice Gaming Headphone',
    },
    {
      // _id: '6',
      name: 'Versace Deodorant',
      slug: 'Versace-Deodorant',
      category: 'fashion',
      image:
        'https://5.imimg.com/data5/MN/HV/MY-7224153/versace-pour-homme-edt-perfume-for-men-200-ml-500x500.png',
      price: 3500,
      countInStock: 7,
      brand: 'versace',
      rating: 5,
      numReviews: 11,
      description: 'Nice Perfume',
    },
    {
      // _id: '7',
      name: 'LG TV',
      slug: 'LG-TV',
      category: 'tech',
      image: 'https://www.lg.com/in/images/tvs/md07549313/32LQ570BPSA-260.jpg',
      price: 3500,
      countInStock: 0,
      brand: 'lg',
      rating: 5,
      numReviews: 11,
      description: '40 INCH OLED',
    },
    {
      // _id: '8',
      name: 'COSMIC BYTE KEYBOARD',
      slug: 'COSMIC-BYTE-KEYBOARD',
      category: 'tech',
      image: 'https://m.media-amazon.com/images/I/61vjNMgYGLL._AC_SL1500_.jpg',
      price: 740,
      countInStock: 10,
      brand: 'cosmic',
      rating: 3.5,
      numReviews: 11,
      description: 'Nice keyboard',
    },
  ],
};

export default data;
